export const QUIZZES = [
  {
    questionNo: 1,
    question: "What is a potato?",
    answer: "vegetable",
    imageUrl: "",
    hint: "type",
  },
  {
    questionNo: 2,
    question: "What is the capital of France?",
    answer: "Paris",
    imageUrl: "",
    hint: "city",
  },
  {
    questionNo: 3,
    question: "What gas do plants absorb from the atmosphere?",
    answer: "Carbon Dioxide",
    imageUrl: "",
    hint: "gas",
  },
  {
    questionNo: 4,
    question: "What is the largest planet in our Solar System?",
    answer: "Jupiter",
    imageUrl: "",
    hint: "planet",
  },
  {
    questionNo: 5,
    question: "Who wrote 'Romeo and Juliet'?",
    answer: "William Shakespeare",
    imageUrl: "",
    hint: "author",
  },
  {
    questionNo: 6,
    question: "What is the boiling point of water in Celsius?",
    answer: "100",
    imageUrl: "",
    hint: "temperature",
  },
  {
    questionNo: 7,
    question: "What element does 'O' represent on the periodic table?",
    answer: "Oxygen",
    imageUrl: "",
    hint: "element",
  },
  {
    questionNo: 8,
    question: "Which animal is known as the 'King of the Jungle'?",
    answer: "Lion",
    imageUrl: "",
    hint: "animal",
  },
  {
    questionNo: 9,
    question: "What is the currency of Japan?",
    answer: "Yen",
    imageUrl: "",
    hint: "currency",
  },
  {
    questionNo: 10,
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
    imageUrl: "",
    hint: "mineral",
  },
];
