import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "~/components/ui/sonner";

import Navbar from "~/app/_components/navbar";
import { cn } from "~/lib/utils";
import "~/styles/globals.css";
import { TRPCReactProvider } from "~/trpc/react";

import AuthProvider from "./_components/authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen w-full")}>
        <AuthProvider>
          <Navbar />
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
